import type { Algorithm } from "./types.ts"
import * as sorts from "./sorts.ts"

export * from "./types.ts"

export const algorithms: Algorithm[] = [
  {
    id: "merge",
    name: "Merge Sort",
    nameKorean: "병합 정렬",
    sort: sorts.mergeSort,
    complexityMultiplier: 1.0,
    timeComplexity: "O(n × log n)",
  },
  {
    id: "selection",
    name: "Selection Sort",
    nameKorean: "선택 정렬",
    sort: sorts.selectionSort,
    complexityMultiplier: 0.25,
    timeComplexity: "O(n²)",
  },
  {
    id: "insertion",
    name: "Insertion Sort",
    nameKorean: "삽입 정렬",
    sort: sorts.insertionSort,
    complexityMultiplier: 0.25,
    timeComplexity: "O(n²)",
  },
  {
    id: "binary-insertion",
    name: "Binary Insertion Sort",
    nameKorean: "이진 삽입 정렬",
    sort: sorts.binaryInsertionSort,
    complexityMultiplier: 0.25,
    timeComplexity: "O(n²)",
  },
  {
    id: "quick",
    name: "Quick Sort",
    nameKorean: "퀵 정렬",
    sort: sorts.quickSort,
    complexityMultiplier: 1.0,
    timeComplexity: "O(n × log n)",
  },
  {
    id: "bubble",
    name: "Bubble Sort",
    nameKorean: "버블 정렬",
    sort: sorts.bubbleSort,
    complexityMultiplier: 0.25,
    timeComplexity: "O(n²)",
  },
  {
    id: "cocktail-shaker",
    name: "Cocktail Shaker Sort",
    nameKorean: "칵테일 쉐이커 정렬",
    sort: sorts.cocktailShakerSort,
    complexityMultiplier: 0.25,
    timeComplexity: "O(n²)",
  },
  {
    id: "gnome",
    name: "Gnome Sort",
    nameKorean: "놈 정렬",
    sort: sorts.gnomeSort,
    complexityMultiplier: 0.25,
    timeComplexity: "O(n²)",
  },
  {
    id: "comb",
    name: "Comb Sort",
    nameKorean: "콤 정렬",
    sort: sorts.combSort,
    complexityMultiplier: 0.5,
    timeComplexity: "O(n × log n)",
  },
  {
    id: "shell",
    name: "Shell Sort",
    nameKorean: "셸 정렬",
    sort: sorts.shellSort,
    complexityMultiplier: 0.5,
    timeComplexity: "O(n^1.5)",
  },
  {
    id: "heap",
    name: "Heap Sort",
    nameKorean: "힙 정렬",
    sort: sorts.heapSort,
    complexityMultiplier: 0.5,
    timeComplexity: "O(n × log n)",
  },
  {
    id: "odd-even",
    name: "Odd-Even Sort",
    nameKorean: "홀짝 정렬",
    sort: sorts.oddEvenSort,
    complexityMultiplier: 0.25,
    timeComplexity: "O(n²)",
  },
  {
    id: "bitonic",
    name: "Bitonic Sort",
    nameKorean: "바이토닉 정렬",
    sort: sorts.bitonicSort,
    complexityMultiplier: 0.5,
    timeComplexity: "O(n × log² n)",
  },
  {
    id: "cycle",
    name: "Cycle Sort",
    nameKorean: "사이클 정렬",
    sort: sorts.cycleSort,
    complexityMultiplier: 0.25,
    timeComplexity: "O(n²)",
  },
  {
    id: "lsd-radix",
    name: "LSD Radix Sort",
    nameKorean: "LSD 기수 정렬",
    sort: sorts.lsdRadixSort,
    complexityMultiplier: 1.0,
    timeComplexity: "O(n × k)",
  },
  {
    id: "msd-radix",
    name: "MSD Radix Sort",
    nameKorean: "MSD 기수 정렬",
    sort: sorts.msdRadixSort,
    complexityMultiplier: 1.0,
    timeComplexity: "O(n × k)",
  },
  {
    id: "bucket",
    name: "Bucket Sort",
    nameKorean: "버킷 정렬",
    sort: sorts.bucketSort,
    complexityMultiplier: 2.0,
    timeComplexity: "O(n + k)",
  },
  {
    id: "counting",
    name: "Counting Sort",
    nameKorean: "카운팅 정렬",
    sort: sorts.countingSort,
    complexityMultiplier: 2.0,
    timeComplexity: "O(n + k)",
  },
  {
    id: "pancake",
    name: "Pancake Sort",
    nameKorean: "팬케이크 정렬",
    sort: sorts.pancakeSort,
    complexityMultiplier: 0.25,
    timeComplexity: "O(n²)",
  },
  {
    id: "bogo",
    name: "Bogo Sort",
    nameKorean: "보고 정렬",
    sort: sorts.bogoSort,
    complexityMultiplier: 0.5,
    timeComplexity: "O((n + 1)!)",
  },
]
